version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      #- DATABASE_HOST=127.0.0.1
  


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "diegoromo_408@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80" 
    depends_on:
      - db
  


  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db